SELECT 
    A.OWNER_NAME__C AS ACCOUNT_OWNER,
    A.NAME AS ACCOUNT_NAME,
    A.ID AS ACCOUNT_ID,
    A.COMMON_ENTITY_NAME__C AS COMMON_ENTITY_NAME,
    A.COMMON_ENTITY_ID__C AS COMMON_ENTITY_ID,
    A.ACCOUNTNUMBER AS ACCOUNT_NUMBER,
    A.TERRITORY_ID__C AS TERRITORY_ID,
    T.WHATID AS WHAT_ID,
    T.ID AS TASK_ID,
    T.OWNERID AS ACTIVITY_OWNER_ID,
    A.OWNER_NAME__C AS ACTIVITY_OWNER_NAME,
    T.SUBJECT AS ACTIVITY_SUBJECT,
    T.DM_DISCUSSION__C AS ACTIVITY_DMC_CHECK_BOX,
    T.ACTIVITYDATE AS ACTIVITY_DATE,
    TO_VARCHAR(T.ACTIVITYDATE, 'MM-01-YYYY') AS ACTIVITY_PERIOD,
    CONTACT.EMAIL AS CONTACT_EMAIL,
    CONTACT.FULL_NAME__C AS CONTACT_NAME,
    CONTACT.DECISION_MAKER__C AS CONTACT_DMC_CHECK_BOX
FROM  
    PRD_ENT_PL_DATALAKE_DB.PHARMA2_SFDC.ACCOUNT A 
LEFT JOIN 
    PRD_ENT_PL_DATALAKE_DB.PHARMA2_SFDC.V_TASK T ON T.WHATID = A.ID
LEFT JOIN 
    PRD_ENT_PL_DATALAKE_DB.PHARMA2_SFDC.V_CONTACT CONTACT ON CONTACT.ID = T.WHOID
WHERE 
    T.ACTIVITYDATE >= '2024-12-01' AND
    T.ACTIVITYDATE <= '2024-12-31' AND
    T.DM_DISCUSSION__C = 'true' AND -- DMC task only
    T.ID = '00THq00007T481eMAB'; -- Example task ID