
--PULL EACH POSSIBLE MONTH START DATE
CREATE OR REPLACE TEMPORARY TABLE CAL_DATE AS

SELECT  CAL_DT
FROM    SBX_PSAS_DB.GX_DA.T_CAL
WHERE   CAL_DT IN ('2024-04-01','2024-05-01','2024-06-01','2024-07-01',
                   '2024-08-01','2024-09-01','2024-10-01','2024-11-01',
                   '2024-12-01','2025-01-01');

--CREATE CUSTOMER & MONTH BASE TABLE                   
CREATE OR REPLACE TEMPORARY TABLE CUST_DATE AS 

SELECT      HIER.CUST_ACCT_ID, 
            CAL_DATE.CAL_DT AS MONTH_START_DT
FROM        SBX_PSAS_DB.SALES_OPS_GOV.V_MASTERS_SFDC_ACCT_ASSIGNMENTS HIER
CROSS JOIN  CAL_DATE;



--FINAL PULL
CREATE OR REPLACE TABLE SBX_PSAS_DB.SALES_OPS_GOV.T_MASTERS_SFDC_PRODUCTIVITY AS 

SELECT      CUST_DATE.CUST_ACCT_ID AS CUST_ACCT_ID,
            CUST_DATE.MONTH_START_DT AS MONTH_START_DT,
            HIER.ACCOUNT_OWNER AS ACCOUNT_OWNER,
            HIER.USER_MANAGER AS MANAGER,
            HIER.CAREER_LEVEL,
            HIER.LEVEL_START_DATE,
            HIER.LEVEL_END_DATE,
            HIER.LEVEL_STATUS_DSCR,
            ACCT.OWNER_NAME__C AS SFDC_ACCOUNT_OWNER,
            ACCT.NAME AS SFDC_ACCOUNT_NAME,
            ACCT.ID AS SFDC_ACCOUNT_ID,
            ACCT.ACCOUNTNUMBER AS SFDC_ACCT_NUMBER,
            ACCT.TERRITORY_ID__C AS SFDC_TERR_ID,
            TASK.WHATID AS TASK_WHAT_ID,
            TASK.ID AS TASK_ID,
            TASK.DM_DISCUSSION__C AS TASK_CALL_DMC_FLAG,
            TASK.OWNERID AS TASK_ACTIVITY_OWNER_ID,
            TASK.SUBJECT AS TASK_SUBJECT,
            TASK.ACTIVITYDATE AS TASK_ACTIVITY_DATE,
            TO_VARCHAR(TASK.ACTIVITYDATE, 'YYYY-MM-01') AS TASK_MONTH_START,
            TASK.CALLTYPE AS TASK_CALL_TYPE,
            TASK.TASKSUBTYPE AS TASK_SUB_TYPE,
            CASE WHEN TASK.DM_DISCUSSION__C = true THEN 1 ELSE 0 END AS TASK_DMC_CALL_CNT
FROM        CUST_DATE
LEFT JOIN   SBX_PSAS_DB.SALES_OPS_GOV.V_MASTERS_SFDC_ACCT_ASSIGNMENTS HIER
ON          LTRIM(CUST_DATE.CUST_ACCT_ID,'0') = LTRIM(HIER.CUST_ACCT_ID,'0')
LEFT JOIN   PRD_ENT_PL_DATALAKE_DB.PHARMA2_SFDC.ACCOUNT ACCT 
ON          LTRIM(HIER.CUST_ACCT_ID, '0') = LTRIM(ACCT.ACCOUNTNUMBER, '0')
LEFT JOIN   PRD_ENT_PL_DATALAKE_DB.PHARMA2_SFDC.V_TASK TASK
ON          LTRIM(TASK.WHATID, '0') = LTRIM(ACCT.ID, '0')
AND         TO_VARCHAR(TASK.ACTIVITYDATE, 'YYYY-MM-01') = CUST_DATE.MONTH_START_DT
AND         TASK.TASKSUBTYPE = 'Call';
